### ISSUE TITLE
Default install of libs in a template project directory

### ISSUE THREAD

**Issue by johanvonboer** [humlab-speech/visible-speech-deployment#49] opened 2021-05-03 07:42 UTC

**Comment by FredrikKarlssonSpeech** [comment] 2021-05-06 11:08
Just to point out that this issue is actually a duplicate of #36 

The packages I see should be in the template dir are:

openxlsx
ggpubr
gt
tidyverse
tidymodels
reindeer
superassp
devtools

(and dependencies)

**Comment by FredrikKarlssonSpeech** [comment] 2021-05-11 05:20
Sorry. I actuallly thought the installation path was stored. Anyway:

https://github.com/tjmahr/tjm.praat


I'll change the install instructions for superassp too.

**Comment by FredrikKarlssonSpeech** [comment] 2021-05-11 05:43
Actually, the issue is with how install_github handles dependencies:

> devtools::install_github("humlab-speech/superassp",dependencies = "Imports")

works (for me).

**Comment by TomasSkotare** [comment] 2024-03-21 15:45
As the current jupyter/R images already handle these packages from what I understand, can we close this issue?

**Closed** 2024-03-25 13:33 UTC
